#!/bin/bash
list="/tmp/list"
nati() {
  ips=()
  network=(${1//\// })
  iparr=(${network[0]//./ })
  if [[ ${network[1]} =~ '.' ]]; then
    netmaskarr=(${network[1]//./ })
  else
    if [[ $((8-${network[1]})) -gt 0 ]]; then
      netmaskarr=($((256-2**(8-${network[1]}))) 0 0 0)
    elif  [[ $((16-${network[1]})) -gt 0 ]]; then
      netmaskarr=(255 $((256-2**(16-${network[1]}))) 0 0)
    elif  [[ $((24-${network[1]})) -gt 0 ]]; then
      netmaskarr=(255 255 $((256-2**(24-${network[1]}))) 0)
    elif [[ $((32-${network[1]})) -gt 0 ]]; then
      netmaskarr=(255 255 255 $((256-2**(32-${network[1]}))))
    fi
  fi
  [[ ${netmaskarr[2]} == 255 ]] && netmaskarr[1]=255
  [[ ${netmaskarr[1]} == 255 ]] && netmaskarr[0]=255
  for i in $(seq 0 $((255-${netmaskarr[0]}))); do
    for j in $(seq 0 $((255-${netmaskarr[1]}))); do
      for k in $(seq 0 $((255-${netmaskarr[2]}))); do
        for l in $(seq 1 $((255-${netmaskarr[3]}))); do
          ips+=( $(( $i+$(( ${iparr[0]}  & ${netmaskarr[0]})) ))"."$(( $j+$(( ${iparr[1]} & ${netmaskarr[1]})) ))"."$(($k+$(( ${iparr[2]} & ${netmaskarr[2]})) ))"."$(($l+$((${iparr[3]} & ${netmaskarr[3]})) )) )
        done
      done
    done
  done
}

nati $1
echo ${ips[@]} | tr " " "\n" > $list
for output in $(cat $list); do
dns=$(host $output | awk '{print $5}' | sed 's/.$//')
        if [ $dns == "3(NXDOMAIN" ]; then
        name="(\e[39mSem entrada no DNS\e[34m)"
        else
        name="(\e[39m$dns\e[34m)"
        fi
    fping -r 1 -t 100 $output > /dev/null
    if [ $? -eq 0 ]; then
    echo -e "\e[34m$output $name \e[39m- \e[32mUP\e[0m"
    else
    echo -e "\e[34m$output $name \e[39m- \e[31mDOWN\e[0m"
    fi
done
rm -f $list
